# Generated by Django 2.1 on 2018-08-31 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('num_ratings', models.PositiveIntegerField(default=0)),
                ('text_content', models.TextField(unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jokes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-average_rating', '-num_ratings'),
            },
        ),
        migrations.CreateModel(
            name='JokeReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('GREEN_BUTTON', 1), ('LEFT', -1), ('RED_BUTTON', -1), ('RIGHT', 1), ('SAVE', 5)], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='jokes.Joke')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='jokereaction',
            unique_together={('joke', 'user')},
        ),
    ]
