# Generated by Django 2.1 on 2018-08-28 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joke',
            options={'ordering': ('average_rating', 'num_ratings')},
        ),
        migrations.AlterModelOptions(
            name='jokerating',
            options={'ordering': ('created_at',)},
        ),
    ]
